# Generated by Django 3.1.1 on 2020-10-01 18:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=25)),
                ('barangay', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('birthdate', models.DateField(blank=True)),
                ('status', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('spouse_name', models.CharField(max_length=100)),
                ('spouse_occupation', models.CharField(max_length=100)),
                ('no_children', models.IntegerField(default=0)),
                ('cimg', models.ImageField(blank=True, null=True, upload_to='customerPic/')),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='customer.person')),
                ('customer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Customer_ID')),
                ('date_registered', models.DateField(blank=True, default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Customer',
            },
            bases=('customer.person',),
        ),
    ]
