# Generated by Django 3.1.1 on 2020-10-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvd',
            name='dimg',
            field=models.ImageField(blank=True, null=True, upload_to='dvdPic/'),
        ),
    ]
