# Generated by Django 3.1.1 on 2020-10-09 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='order_id')),
                ('customer_name', models.CharField(max_length=30)),
                ('dvd_title', models.CharField(max_length=30)),
                ('order_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(default=1)),
                ('sent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
